---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

version: 1

name: hyprite

description: "Personal Fedora Atomic image based on Universal Blue, with Hyprland, Noctalia and Noctalia Greeter."

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:

  # -----------------------------------------------
  # RPM repositories
  # -----------------------------------------------

  #- type: dnf
  #  repos:
  #    files:
  #      - https://repos.fyralabs.com/terra%OS_VERSION%/terra.repo

  # -----------------------------------------------
  # Repositories
  # -----------------------------------------------

  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo

      copr:
        - lionheartp/hyprland


  # -----------------------------------------------
  # Terra repository
  # -----------------------------------------------

  #- type: script
  #  snippets:
  #    - |
  #      curl -fsSL https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo \
  #        -o /etc/yum.repos.d/terra.repo#
  #
  #      dnf5 install -y terra-release

  # -----------------------------------------------
  # System packages
  # -----------------------------------------------

  - type: dnf
    install:
      packages:

        # Basic CLI
        - mc
        # - htop   # installed in base-main
        - micro
        - git
        # - curl   # installed in base-main
        # - wget   # installed in base-main
        # - rsync  # installed in base-main

        # Hyprland
        - hyprland
        - hyprpaper
        - hyprpicker
        - hypridle
        - hyprlock
        - hyprpolkitagent

        # Hyprland portals
        # - xdg-desktop-portal # installed in base-main
        - xdg-desktop-portal-hyprland
        # - xdg-desktop-portal-gtk # installed in base-main

        # Login / greeter
        - greetd
        - noctalia-greeter

        # Noctalia
        - noctalia

        # D-Bus / authentication
        # - dbus   # installed in base-main
        # - polkit # installed in base-main

        # Audio
        # - pipewire # installed in base-main
        # - pipewire-pulseaudio # installed in base-main
        # - wireplumber # installed in base-main

        # Network
        # - NetworkManager # installed in base-main

        # Bluetooth
        # - bluez  # installed in base-main
        - bluez-tools

        # File/archive utilities
        # - unzip  # installed in base-main

        # Fonts
        - google-noto-fonts-common
        # - google-noto-emoji-fonts # installed in base-main


  # -----------------------------------------------
  # greetd configuration
  # -----------------------------------------------

  - type: files
    files:
      - source: system
        destination: /


  # -----------------------------------------------
  # Enable greetd
  # -----------------------------------------------

  - type: systemd
    system:
      enabled:
        - greetd.service


  # -----------------------------------------------
  # Sign image
  # -----------------------------------------------

  - type: signing